# Webpage
websiteTitle: "Eric's Website"
websiteIcon: "/favicon.svg"

# Postgres database
data:
  - dbname: WywyWebsite
    tables:
      - tableName: daily
        read: true
        write: true
        entrytype: form
        schema:
          # Please note that the datatype is what the PostgreSQL database will recognize (e.g. Typescript has no way of differentiating an integer from a float).
          - name: Date
            parser: date # the datatype that the parser should attempt to cast to
            datatype: timestamp
            entrytype: calendar time
            description: The estimate of when you gained conciousness at the start of this (sleep-based) day.

          - name: Work Ethic
            datatype: int
            entrytype: linearSlider
            comments: true
            description: How much drive did you have to do work today?

          - name: Time Efficiency
            datatype: int
            entrytype: linearSlider
            comments: true
            description: How much % of time did you productivity exploit to achieve your (any type of) goals today? Compare to the feasible maximum.

          - name: Happiness
            datatype: int
            entrytype: linearSlider
            comments: true
            description: What % are you feeling today?

          - name: Awareness
            datatype: int
            entrytype: linearSlider
            comments: true
            description: How alert are you today? Tired? Focused?

          - name: Sleep Quality
            datatype: int
            entrytype: linearSlider
            comments: true
            description: How would you rate you sleep quality?

          - name: Sleep Behaviour
            datatype: int
            entrytype: linearSlider
            comments: true
            description: How well did you actions today facilitate a good night's rest? The importance is less on how good you sleep and moreso about how good the actions are.

      - tableName: events
        read: true
        write: true
        entrytype: timer
        tagging: true
        schema:
          - name: Start Time
            datatype: timestamp
            entrytype: calendar time

          - name: End time
            datatype: timestamp
            entrytype: calendar time

          # - name: Duration
          #   invertible: true
          #   datatype: interval
          #   entrytype: duration textbox
          #   description: An estimate related to the event length. Positive values represent how long the event occured for. Negative values represent how long the event did not actively occur inside the respective time interval.
        descriptors:
          - name: Bathroom
            schema:
              - name: Bathroom Type
                datatype: enum
                entrytype: radio
                values: ["pee", "poo"]
          - name: Travel
            schema:
              - name: Source
                datatype: string
                entrytype: textbox

              - name: Source Resolution
                datatype: enum
                entrytype: radio
                values: ["region", "building", "room"]

              - name: Destination
                datatype: string
                entrytype: textbox

              - name: Destination Resolution
                datatype: enum
                entrytype: radio
                values: ["region", "building", "room"]
          - name: Shower
            schema:
              - name: Shampoo
                datatype: boolean
                entrytype: switch
                description: Was shampoo used?
              - name: Body Wash
                datatype: boolean
                entrytype: switch
                description: Was body wash used?
          - name: Dental
            schema:
              - name: Waterpik
                datatype: boolean
                entrytype: switch
                description: Did you rinse with Waterpik?
              - name: Toothbrush
                datatype: boolean
                entrytype: switch
                description: Did you brush your teeth?
              - name: Floss
                datatype: boolean
                entrytype: switch
                description: Did you floss, not including the bridge?
              - name: Bridge Floss
                datatype: boolean
                entrytype: switch
                description: Did you floss the teeth under your bridge?
